---
- name: Install Postgresql for AWX
  hosts: all, !local
  tasks:
    - name: install repo
      ansible.builtin.git:
        repo: https://github.com/system-dev-formations/todo-flask-postgres.git
        dest: /home/{{ ansible_user }}
    - name: Set up todos.sql script in docker container
      shell: docker cp /home/{{ ansible_user }}/sql/todos.sql db:/tmp
    - name: Add container db to in-memory inventory
      add_host:
        name: db
        ansible_connection: docker
      changed_when: false