---
- name: Install Postgresql for AWX
  hosts: all, !local
  tasks:
    - name: install repo
      ansible.builtin.git:
        repo: https://github.com/system-dev-formations/todo-flask-postgres.git
        dest: /home/{{ ansible_user }}/todo-flask-postgres
    - name: Set up todos.sql script in docker container
      shell: docker cp /home/{{ ansible_user }}/todo-flask-postgres/sql/todos.sql db:/tmp
    - name: Add container db to in-memory inventory
      add_host:
        name: db
        ansible_connection: docker
      changed_when: false
    - name: run command in container db
      delegate_to: db
      remote_user: postgres
      raw: psql -l | grep tododb | wc -l
      register: result
    - name: Return value
      debug:
        msg: "{{ result.stdout | trim }}"
    - name: Create database
      delegate_to: db
      remote_user: postgres
      raw: psql -c 'create database tododb;'
      when: result.stdout | trim | int == 0