version: '3'

volumes:
  data:


networks:
  lan_network:
    driver: bridge

services:
  todoapplication:
      hostname: todo
      build: .
      ports:
        - 32500:5000
      links:
        - db:postgres
      depends_on:
        - db
      networks:
        -  lan_network

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4
    links:
      - db:postgres
    depends_on:
      - db
    ports:
      - 30100:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ambient-it@gmail.com
      PGADMIN_DEFAULT_PASSWORD: p4ssw0rd
    networks:
      - lan_network

  db:
    hostname: postgres
    image: bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/bitnami/postgresql
      - ./sql:/tmp
    ports:
      - 32432:5432
    networks:
      -  lan_network