---
- name: Install repo and create database on remote
  hosts: all, !local
  tasks:
    - name: install repo
      shell: git clone --no-checkout https://github.com/system-dev-formations/todo-flask-postgres.git
      args:
        chdir:  /home/{{ ansible_user }}
    - name: Checkout files
      shell: git reset
      args:
        chdir: /home/{{ ansible_user }}/todo-flask-postgres
    - name: Checkout create-database file
      shell: git checkout origin/master create-database.yml
      args:
        chdir: /home/{{ ansible_user }}/todo-flask-postgres
    - name: Checkout inventory file
      shell: git checkout origin/master inventory
      args:
        chdir: /home/{{ ansible_user }}/todo-flask-postgres
    - name: Create database tododb
      shell: ansible-playbook -i inventory create-database.yml
      args:
        chdir: /home/{{ ansible_user }}/todo-flask-postgres