---
- hosts: all
  become: true
  tasks:
    - name: Create postgresql container
      docker_container:
        name: 'db'
        image: postgres
        state: 'started'
        env:
          POSTGRES_PASSWORD: 'password' # Beware: in some version is POSTGRESQL_PASSWORD
        ports:
          - "6432:5432"
        volumes:
          - "/opt/postgres:/var/lib/postgresql/data"
      register: db_cont_metadata
    - name: Add container db to in-memory inventory
      add_host:
        name: db
        ansible_user: postgres
        ansible_connection: docker
      changed_when: false
    - name: run command in container db
      delegate_to: db
      raw: psql -l | grep tododb | wc -l
      register: result
    - name: Return value
      debug:
        msg: "{{ result.stdout | trim }}"
    - name: Create database
      delegate_to: db
      raw: psql -c 'create database tododb;'
      when: result.stdout | trim | int == 0




