---
- name: Install repo and create database on remote
  hosts: all
  tasks:
    - name: set up current repo
      git:
        repo: https://github.com/system-dev-formations/todo-flask-postgres.git
        dest: /home/{{ ansible_ssh_user }}
        update: yes
        version: master
    - name: run install postgresql container and check
      shell: ansible-playbook -i inventory create-database.yml --limit local
      args:
        chdir: /home/{{ ansible_ssh_user }}/todo-flask-postgres/